#version 460
#extension GL_EXT_ray_tracing : enable

layout(binding=0,set=0,rgba8) uniform image2D image;
layout(binding=1,set=0) uniform accelerationStructureEXT topLevelAS;
layout(binding=2,set=0) uniform CameraProperties
{
	mat4 view;
	mat4 proj;
	int samples;
 }cam;

struct stHitValue {
vec3 color;
bool miss;
};

layout(location=0) rayPayloadEXT stHitValue hitValue;

vec3 traceRay(vec2 d) {

	vec4 origin = inverse(cam.view) * vec4(0,0,0,1);
	vec4 target = inverse(cam.proj) * vec4(d.x, d.y, 1, 1) ;
	vec4 direction = inverse(cam.view)*vec4(normalize(target.xyz), 0) ;

	//ortho

	//vec4 origin = inverse(cam.view) * inverse(cam.proj) * vec4(d.x, d.y, 0, 1);
	//vec4 direction = inverse(cam.view) * vec4(0, 0, -1, 0);

	float tmin = 0.001;
	float tmax = 10000.0;
	hitValue.color = vec3(0.0);
	hitValue.miss = false;
	traceRayEXT(topLevelAS,gl_RayFlagsOpaqueEXT,0xff,0,0,0,origin.xyz,tmin,direction.xyz,tmax,0);
	return hitValue.color;
}

void main()
{
vec3 finalColor = vec3(0.0);

float jitter = 0.5 / cam.samples;

for (int i = 1; i <= cam.samples; i++) 
{
	for (int j = 1; j <= cam.samples; j++)  
	{
			const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy)+vec2(i * jitter, j * jitter);
			const vec2 inUV = pixelCenter/vec2(gl_LaunchSizeEXT.xy);
			vec2 d = inUV*2.0-1.0;

			vec3 color = traceRay(d);
	
		finalColor += color;
	}
}
finalColor /= (cam.samples*cam.samples);

imageStore(image,ivec2(gl_LaunchIDEXT.xy),vec4(finalColor,0.0));
}